#!/bin/bash

# Set up aliases and such for doing a presentation with MakeDemo
# Copyright (c) 2018 Benjamin Holt -- MIT License

RunAs=`echo "$0" | sed -nE 's/(.*)(demonow)$/\2/p'`

if [ -z "$1" -o "$1" == "-h" -o "$1" == "--help" ]; then
  cat <<USAGE
usage:
source demonow DIR          Set env vars and aliases based on DIR to set up
                            your terminal for presenting with MakeDemo. Must
                            be sourced for the setup to stick
source demonow -c|--clear   Clears the MakeDemoDir env variable and returns
       demonow [-h|--help]  Print this message and exit
USAGE
  if [ "$RunAs" == "demonow" ]; then
    exit 0  # Exit if run as itself
  else
    unset RunAs
    return  # Return if run indirectly (ie sourced)
  fi
fi

if [ "$RunAs" == "demonow" ]; then
  echo "Must be run with 'source' for the setup to stick"
  exit 1  # Not useful when run as itself
fi
unset RunAs

if [ "$1" == "-c" -o "$1" == "--clear" ]; then  # FIXME: Completely cleaning up again is a non-goal, so maybe better not have the option at all?
  unset MakeDemoDir
  echo "Cleared"
  return
fi

MakeDemoDir=$1
export MakeDemoDir
echo "Updated environment"

complete -C "$MakeDemoDir/compmake" make
echo "Added make target tab-completion"

alias n="source $MakeDemoDir/makenext"
alias b="n -b"
alias bb="b 1"
alias bbb="b 2"
# alias help

alias list="make list"
alias seq="cat sequence.tmp.mk"
echo "Added aliases"

# Force sequence file to update
touch -t "200001010000" "sequence.tmp.mk"
make sequence | grep "Refreshed"  # HACK: quiet spurious output

###
