# Example Makefile

default: list  #M Target to run if none is specified

# Requires https://github.com/inventhouse/MakeDemo
# $ path/to/MakeDemo/demoinit
# $ source ./demonow
include $(MakeDemoDir)/MakeDemo.make
ChunkFile := "chunks.txt"

## Example target ##
hello:  ## Say hello
	@echo "Hello demo!"

include sequence.tmp.mk
# # #
